### ISSUE TITLE
About train the model

### ISSUE THREAD

**Issue by xuedue** [Hzzone/PFA-GAN#1]
Hello, author, thank you for sharing.

Regarding the training of the model, I have a few questions.

1. Does this network have to be trained in parallel? Can serial training be used (on a graphics card)?

2. If  train on the Morph dataset and use 256*256 images for training, what is the hardware environment used and the time required?

Looking forward to your reply.

**Comment by Hzzone** [comment]
You can use https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html#torch.nn.DataParallel, but I am not sure it works well.

**Comment by ajithvallabai** [comment]
@xuedue how did u get Morph dataset , did u purchased it ?

**Comment by Hzzone** [comment]
The morph dataset should be purchased from the official website.

**Comment by ajithvallabai** [comment]
thanks
