### ISSUE TITLE
About the hyperparameters

### ISSUE THREAD

**Issue by husterlf** [Hzzone/PFA-GAN#2]
Could you tell me how to choose the hyperparameters?
Are the following parameters right?
`python3 -m torch.distributed.launch main.py --dataset_name=cacd --name=cacd --alpha=0.15 --pix_loss_weight=0.5 --id_loss_weight=0.02 --gan_loss_weight=0.8 --age_loss_weight=0.4`

**Comment by Hzzone** [comment]
Not at all. You should use a large gan_loss_weight to get better image quality. The age loss is to obtain a better age accuracy while the id loss maintains the identity loss. You should start from a large gan_loss_weight and a small id loss weight. Then, you may need to gradually increase the id loss weight. Last, it is ok to tune the age loss weight.

**Comment by husterlf** [comment]
> Not at all. You should use a large gan_loss_weight to get better image quality. The age loss is to obtain a better age accuracy while the id loss maintains the identity loss. You should start from a large gan_loss_weight and a small id loss weight. Then, you may need to gradually increase the id loss weight. Last, it is ok to tune the age loss weight.

Thanks a lot, PhD! 
Can you provide me with 'vgg_face' and 'age_classifier' models?
