### ISSUE TITLE
CACD dataset usage

### ISSUE THREAD

**Issue by ajithvallabai** [Hzzone/PFA-GAN#4]
Is it compulsory to preprocess with Face++ API to achieve the results of paper, Is there any other opensource method . 
Is it possible to release the preprocessed dataset in a gdrive link ?

**Comment by Hzzone** [comment]
It is not compulsory, MTCNN maybe also ok.

**Comment by ajithvallabai** [comment]
@Hzzone  is it possible to share train.txt file and test.txt file

**Comment by Beekam-G** [comment]
How can I get MOrph datasets?
