### ISSUE TITLE
'DeepFaceVGG_RGB.pth'

### ISSUE THREAD

**Issue by sabbbin** [Hzzone/PFA-GAN#5]
i am trying to run your code
But i didn't understand  from where we get 'DeepFaceVGG_RGB.pth'

**Comment by Hzzone** [comment]
Thanks for your interest, this pre-trained model is converted from https://www.robots.ox.ac.uk/~vgg/software/vgg_face/ 
 (Caffe version) by https://github.com/vadimkantorov/caffemodel2pytorch.

**Comment by AstuWeb** [comment]
ValueError: empty range for randrange() (0,0, 0)
