### ISSUE TITLE
ValueError: empty range for randrange() (0,0, 0)

### ISSUE THREAD

**Issue by AstuWeb** [Hzzone/PFA-GAN#7]

**Comment by AstuWeb** [comment]
PLEASE HELP ME

**Comment by AstuWeb** [comment]
File "/home/cv-lab/PFA-GAN-master/dataset.py", line 120, in __getitem__
    index = random.randint(0, len(self.label_group_images[true_label])-1)

**Comment by Hzzone** [comment]
You need to generate the label files.

**Comment by AstuWeb** [comment]
YES
